README.md
src/FoxIDs.Control/appsettings.json
src/FoxIDs.Shared/Infrastructure/Logging/TelemetryLogger.cs
src/FoxIDs.Shared/Models/Config/Settings.cs
src/FoxIDs/Logic/Tracks/SendEmailLogic.cs
src/FoxIDs/Startup.cs
src/FoxIDs/appsettings.json
test/FoxIDs.UnitTests/AccountLogicTests.cs
test/FoxIDs.UnitTests/ClaimTransformationsLogicTests.cs
test/FoxIDs.UnitTests/Helpers/TelemetryLoggerHelper.cs

Add LogGlobalTrace switch.

---

azuredeploy.json

Deployment slot added.

---

src/FoxIDs.Control/Controllers/Tenants/TTenantController.cs
src/FoxIDs.Control/Controllers/Tracks/TTrackKeyContainedController.cs
src/FoxIDs.Control/Controllers/Tracks/TTrackKeyTypeController.cs
src/FoxIDs.ControlShared/Models/Api/Tracks/TrackKey.cs
src/FoxIDs.Shared/Extensions/X509Certificate2Extensions.cs
src/FoxIDs.Shared/Logic/MasterTenantLogic.cs
src/FoxIDs.Shared/Logic/Tracks/TrackLogic.cs
src/FoxIDs.Shared/Models/Routes/RouteBinding.cs
src/FoxIDs/Logic/FailingLoginLogic.cs
src/FoxIDs/Logic/Tracks/AccountActionLogic.cs
tools/FoxIDs.SeedTool/SeedLogic/MasterTenantDocumentsSeedLogic.cs

Change TenantDashTrackName to TenantNameDotTrackName.

Add track name to cert name and support removing '-' in prod.

---

README.md
docs/control.md
docs/getting-started.md
docs/index.md
src/FoxIDs.ControlClient/Shared/TenantOidcRedirectToLogin.razor
src/FoxIDs/Controllers/Site/WController.cs
src/FoxIDs/FoxIDs.csproj
src/FoxIDs/Views/W/Index.cshtml
src/FoxIDs/wwwroot/lib/jquery-validation/dist/jquery.validate.js

FoxIDs Site index

---

src/FoxIDs/Logic/Saml/SamlAuthnUpLogic.cs
src/FoxIDs/Logic/Saml/SamlLogoutUpLogic.cs

Saml 2.0 logout request only add CSP Frame Form Action Url on post binding

Saml 2.0 authn request add CSP Frame Form Action Url on post binding.

---

src/FoxIDs.Control/FoxIDs.Control.csproj
src/FoxIDs/FoxIDs.csproj

https://docs.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/duplicate-files-in-output

ErrorOnDuplicatePublishOutputFiles = false, from:

---

src/FoxIDs.Control/FoxIDs.Control.csproj
src/FoxIDs.ControlClient/FoxIDs.ControlClient.csproj
src/FoxIDs.ControlShared/FoxIDs.ControlShared.csproj
src/FoxIDs.Shared/FoxIDs.Shared.csproj
src/FoxIDs.Shared/Infrastructure/Hosting/ProxyHeadersMiddleware.cs
src/FoxIDs.SharedBase/FoxIDs.SharedBase.csproj
src/FoxIDs/FoxIDs.csproj

check if client IP Is Localhost

---

src/FoxIDs.Control/FoxIDs.Control.csproj
src/FoxIDs.Control/Infrastructure/Queue/BackgroundQueueService.cs
src/FoxIDs.Control/Logic/Queues/DownPartyAllowUpPartiesQueueLogic.cs
src/FoxIDs.Control/Models/Queue/QueueEnvelope.cs
src/FoxIDs.ControlClient/FoxIDs.ControlClient.csproj
src/FoxIDs.ControlShared/FoxIDs.ControlShared.csproj
src/FoxIDs.Shared/FoxIDs.Shared.csproj
src/FoxIDs.Shared/Infrastructure/Logging/TelemetryScopedLogger.cs
src/FoxIDs.SharedBase/FoxIDs.SharedBase.csproj
src/FoxIDs/FoxIDs.csproj

TelemetryScopedLogger not logging scope properties in event bug.

Background queue use logging settings.

---

docs/deployment.md
src/FoxIDs.Control/FoxIDs.Control.csproj
src/FoxIDs.ControlClient/FoxIDs.ControlClient.csproj
src/FoxIDs.ControlShared/FoxIDs.ControlShared.csproj
src/FoxIDs.Shared/FoxIDs.Shared.csproj
src/FoxIDs.SharedBase/FoxIDs.SharedBase.csproj
src/FoxIDs/FoxIDs.csproj

Only use SemVer compatible versions (MAJOR.MINOR.PATCH)

---

docs/up-party-howto-oidc-nets-eid-broker.md
src/FoxIDs.Control/FoxIDs.Control.csproj
src/FoxIDs.Control/Logic/ValidateOAuthOidcPartyLogic.cs
src/FoxIDs.ControlClient/FoxIDs.ControlClient.csproj
src/FoxIDs.ControlClient/Models/ViewModels/Parties/OidcUpClientViewModel.cs
src/FoxIDs.ControlClient/Pages/Components/EOidcUpParty.razor
src/FoxIDs.ControlShared/FoxIDs.ControlShared.csproj
src/FoxIDs.ControlShared/Models/Api/Parties/OidcUpClient.cs
src/FoxIDs.Shared/FoxIDs.Shared.csproj
src/FoxIDs.Shared/Logic/Parties/OidcDiscoveryReadLogic.cs
src/FoxIDs.Shared/Models/Parties/OAuthUpClient.cs
src/FoxIDs.Shared/Models/Parties/OidcUpClient.cs
src/FoxIDs.SharedBase/Constants.cs
src/FoxIDs.SharedBase/FoxIDs.SharedBase.csproj
src/FoxIDs/FoxIDs.csproj
src/FoxIDs/Logic/Oidc/OidcAuthUpLogic.cs
tools/FoxIDs.SeedTool/SeedLogic/RiskPasswordSeedLogic.cs

Support to read claims from UserInfo endpoint in OIDC up-party.

---

src/FoxIDs.Control/FoxIDs.Control.csproj
src/FoxIDs.ControlClient/FoxIDs.ControlClient.csproj
src/FoxIDs.ControlShared/FoxIDs.ControlShared.csproj
src/FoxIDs.Shared/FoxIDs.Shared.csproj
src/FoxIDs.SharedBase/FoxIDs.SharedBase.csproj
src/FoxIDs/FoxIDs.csproj
src/FoxIDs/Logic/SequenceLogic.cs
src/FoxIDs/Views/Error/Index.cshtml

Show error retry button using correct property.

Set values before validation in SequenceLogic, to enable error handling.

---

src/FoxIDs.Control/Controllers/Tenants/TMyTenantLogUsageController.cs
src/FoxIDs.Control/Controllers/Tenants/TTenantLogUsageController.cs
src/FoxIDs.Control/FoxIDs.Control.csproj
src/FoxIDs.Control/Logic/UsageLogLogic.cs
src/FoxIDs.ControlClient/FoxIDs.ControlClient.csproj
src/FoxIDs.ControlClient/Models/ViewModels/Tracks/UsageLogIncludeTypes.cs
src/FoxIDs.ControlClient/Models/ViewModels/Tracks/UsageLogRequestViewModel.cs
src/FoxIDs.ControlClient/Pages/Components/EUsageLogItem.razor
src/FoxIDs.ControlClient/Pages/LogUsages.cs
src/FoxIDs.ControlShared/FoxIDs.ControlShared.csproj
src/FoxIDs.ControlShared/Models/Api/Tracks/Logs/UsageLogRequest.cs
src/FoxIDs.ControlShared/Models/Api/Tracks/Logs/UsageLogTypes.cs
src/FoxIDs.Shared/FoxIDs.Shared.csproj
src/FoxIDs.SharedBase/FoxIDs.SharedBase.csproj
src/FoxIDs/FoxIDs.csproj

Thange usage log enum: UsageLogTypes

Log usage add Key Vault managed certificates.

---

docs/deployment.md
docs/howto-saml-2.0-context-handler.md
docs/reverse-proxy.md
docs/samples.md
src/FoxIDs.Control/FoxIDs.Control.csproj
src/FoxIDs.ControlClient/FoxIDs.ControlClient.csproj
src/FoxIDs.ControlShared/FoxIDs.ControlShared.csproj
src/FoxIDs.ResourceTranslateTool/Logic/ResourceLogic.cs
src/FoxIDs.Shared/FoxIDs.Shared.csproj
src/FoxIDs.Shared/Models/Master/Resources/EmbeddedResource.json
src/FoxIDs.SharedBase/FoxIDs.SharedBase.csproj
src/FoxIDs/FoxIDs.csproj

"en" in top of the supported_cultures list.

---

src/FoxIDs.Control/Infrastructure/Hosting/ServiceCollectionExtensions.cs
src/FoxIDs.Control/Properties/launchSettings.json
src/FoxIDs.Control/appsettings.Development.json
src/FoxIDs.Shared/FoxIDs.Shared.csproj
src/FoxIDs.Shared/Infrastructure/Hosting/ServiceCollectionExtensions.cs
src/FoxIDs.Shared/Logic/Master/EmbeddedResourceLogic.cs
src/FoxIDs.Shared/Logic/Parties/OidcDiscoveryReadLogic.cs
src/FoxIDs.Shared/Logic/Parties/SamlMetadataReadLogic.cs
src/FoxIDs.Shared/Models/Config/FileDataSettings.cs
src/FoxIDs.Shared/Models/Config/Options/DataStorageOptions.cs
src/FoxIDs.Shared/Repository/Files/FileDataRepository.cs
src/FoxIDs.Shared/Repository/PostgreSQL/PgMasterDataRepository.cs
src/FoxIDs.Shared/Repository/PostgreSQL/PgTenantDataRepository.cs
src/FoxIDs/Infrastructure/Hosting/ServiceCollectionExtensions.cs
src/FoxIDs/Logic/OAuth/OAuthAuthUpLogic.cs
src/FoxIDs/Logic/Oidc/OidcAuthUpLogic.cs
src/FoxIDs/Properties/launchSettings.json
src/FoxIDs/appsettings.Development.json

Seems to already be in working order in local tests.

PostgreSQL implementation for repositories

---

Kubernetes/k8s-foxids-deployment.yaml
src/FoxIDs.Control/FoxIDs.Control.csproj
src/FoxIDs.Control/Infrastructure/Hosting/OpenSearchClientQueryLog.cs
src/FoxIDs.Control/Infrastructure/Hosting/ServiceCollectionExtensions.cs
src/FoxIDs.Control/Logic/Logs/LogOpenSearchLogic.cs
src/FoxIDs.Control/Logic/Logs/UsageLogOpenSearchLogic.cs
src/FoxIDs.ControlClient/FoxIDs.ControlClient.csproj
src/FoxIDs.ControlShared/FoxIDs.ControlShared.csproj
src/FoxIDs.Shared/FoxIDs.Shared.csproj
src/FoxIDs.Shared/Infrastructure/Hosting/ServiceCollectionExtensions.cs
src/FoxIDs.Shared/Infrastructure/Logging/OpenSearchTelemetryLogger.cs
src/FoxIDs.SharedBase/FoxIDs.SharedBase.csproj
src/FoxIDs/FoxIDs.csproj

Separate OpenSearchClient for query log.
OpenSearchClient throw exceptions.

k8s add Stdout settings.

---

src/FoxIDs.Control/Controllers/Master/MRiskPasswordController.cs
src/FoxIDs.Control/FoxIDs.Control.csproj
src/FoxIDs.ControlClient/FoxIDs.ControlClient.csproj
src/FoxIDs.ControlShared/FoxIDs.ControlShared.csproj
src/FoxIDs.Shared/FoxIDs.Shared.csproj
src/FoxIDs.Shared/Repository/CosmosDb/CosmosDbMasterDataRepository.cs
src/FoxIDs.Shared/Repository/Files/FileMasterDataRepository.cs
src/FoxIDs.Shared/Repository/IMasterDataRepository.cs
src/FoxIDs.Shared/Repository/MasterDataRepositoryBase.cs
src/FoxIDs.Shared/Repository/MongoDb/MongoDbMasterDataRepository.cs
src/FoxIDs.Shared/Repository/PostgreSql/PgMasterDataRepository.cs
src/FoxIDs.SharedBase/FoxIDs.SharedBase.csproj
src/FoxIDs/FoxIDs.csproj
tools/FoxIDs.SeedTool/Program.cs
tools/FoxIDs.SeedTool/SeedLogic/RiskPasswordSeedLogic.cs

Risk passwords support to delete all in MongoDB.

MongoDB support to delete all items in a partition.

---

src/FoxIDs.Control/Controllers/Master/MFilterPlanController.cs
src/FoxIDs.Control/Controllers/Parties/TFilterDownPartyController.cs
src/FoxIDs.Control/Controllers/Parties/TFilterUpPartyController.cs
src/FoxIDs.Control/Controllers/TenantResources/TFilterResourceNameController.cs
src/FoxIDs.Control/Controllers/Tenants/TFilterTenantController.cs
src/FoxIDs.Control/Controllers/Tracks/TFilterExternalUserController.cs
src/FoxIDs.Control/Controllers/Tracks/TFilterTrackController.cs
src/FoxIDs.Control/Controllers/Tracks/TFilterUserController.cs
src/FoxIDs.Control/FoxIDs.Control.csproj
src/FoxIDs.Control/Logic/Logs/UsageLogOpenSearchLogic.cs
src/FoxIDs.ControlClient/FoxIDs.ControlClient.csproj
src/FoxIDs.ControlClient/Pages/Settings/Plans.cs
src/FoxIDs.ControlShared/FoxIDs.ControlShared.csproj
src/FoxIDs.Shared/FoxIDs.Shared.csproj
src/FoxIDs.SharedBase/FoxIDs.SharedBase.csproj
src/FoxIDs/FoxIDs.csproj

Change DB Contains to StringComparison.CurrentCultureIgnoreCase.

OpenSearch usage log support empty log.

---

src/FoxIDs.Control/FoxIDs.Control.csproj
src/FoxIDs.ControlClient/FoxIDs.ControlClient.csproj
src/FoxIDs.ControlClient/Pages/Certificates.razor
src/FoxIDs.ControlShared/FoxIDs.ControlShared.csproj
src/FoxIDs.Shared/FoxIDs.Shared.csproj
src/FoxIDs.Shared/Models/Config/OptionsSettings.cs
src/FoxIDs.SharedBase/FoxIDs.SharedBase.csproj
src/FoxIDs/FoxIDs.csproj

Change default options in code, to match config.

Always show cert change in Client.

---

src/FoxIDs.Control/FoxIDs.Control.csproj
src/FoxIDs.Control/Logic/Logs/LogOpenSearchLogic.cs
src/FoxIDs.ControlClient/FoxIDs.ControlClient.csproj
src/FoxIDs.ControlShared/FoxIDs.ControlShared.csproj
src/FoxIDs.Shared/FoxIDs.Shared.csproj
src/FoxIDs.Shared/Models/Parties/SamlUpParty.cs
src/FoxIDs.Shared/Models/Parties/UpParty.cs
src/FoxIDs.SharedBase/FoxIDs.SharedBase.csproj
src/FoxIDs/FoxIDs.csproj

OpenSerch log search support unlimited property values.

Add default get operator to UpParty.Issuer.

---

src/FoxIDs.Control/FoxIDs.Control.csproj
src/FoxIDs.ControlClient/FoxIDs.ControlClient.csproj
src/FoxIDs.ControlClient/Shared/Components/FInputBase.cs
src/FoxIDs.ControlShared/FoxIDs.ControlShared.csproj
src/FoxIDs.Shared/FoxIDs.Shared.csproj
src/FoxIDs.Shared/Infrastructure/Hosting/ServiceCollectionExtensions.cs
src/FoxIDs.Shared/Infrastructure/Logging/OpenSearchTelemetryLogger.cs
src/FoxIDs.SharedBase/FoxIDs.SharedBase.csproj
src/FoxIDs/FoxIDs.csproj

Client support nullable enum.

---

Kubernetes/k8s-foxids-ingress-deployment.yaml
src/FoxIDs.Control/FoxIDs.Control.csproj
src/FoxIDs.ControlClient/FoxIDs.ControlClient.csproj
src/FoxIDs.ControlClient/Models/ViewModels/Tenants/CustomerViewModel.cs
src/FoxIDs.ControlShared/FoxIDs.ControlShared.csproj
src/FoxIDs.Shared/FoxIDs.Shared.csproj
src/FoxIDs.SharedBase/FoxIDs.SharedBase.csproj
src/FoxIDs/FoxIDs.csproj

Add k8s comment

---

src/FoxIDs.Shared/FoxIDs.Shared.csproj

ref https://github.com/ITfoxtec/FoxIDs/issues/1107

Upgrade PgKeyValueDB to 1.0.1

---

src/FoxIDs.Shared/FoxIDs.Shared.csproj
test/FoxIDs.IntegrationTests/AccountLogicTests.cs

Upgrade PgKeyValueDB and fix test

---

src/FoxIDs.Shared/FoxIDs.Shared.csproj
src/FoxIDs.Shared/Repository/PostgreSql/PgTenantDataRepository.cs
test/FoxIDs.IntegrationTests/AccountLogicTests.cs

ref https://github.com/ITfoxtec/FoxIDs/issues/1132
NOTE: Intended to be rebased on/after merge of https://github.com/ITfoxtec/FoxIDs/pull/1134.

PgTenantDataRepository add application level constraint for AdditionalIds

---

src/FoxIDs.Shared/FoxIDs.Shared.csproj

ref https://github.com/ITfoxtec/FoxIDs/issues/1255

Upgrade PgKeyValueDB
